# Generated by Django 5.1 on 2025-01-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
        ('doctor', '0004_reviewer'),
        ('patient', '0002_alter_patinet_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appoinment_status',
            new_name='appointment_status',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appoinment_type',
            new_name='appointment_type',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patinet',
        ),
    ]
