# Generated by Django 5.1 on 2025-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=12)),
                ('problem', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ContactUs',
            },
        ),
    ]
